[build]
  publish = "."

[context.production]
  [context.production.environment]
    SITE_ENV = "production"

[context.branch-deploy]
  [context.branch-deploy.environment]
    SITE_ENV = "staging"

[context.deploy-preview]
  [context.deploy-preview.environment]
    SITE_ENV = "preview"
